// Code generated by _gen/main.go DO NOT EDIT
/*
Copyright 2015-2024 Gravitational, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package provider

import (
	"context"
	"fmt"

	foov1 "github.com/gravitational/teleport/api/gen/proto/go/teleport/foo/v1"
	
	"github.com/gravitational/teleport/api/utils/retryutils"
	"github.com/gravitational/trace"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/tfsdk"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/gravitational/teleport/lib/scopes"
	"strings"

	schemav1 "github.com/gravitational/teleport/integrations/terraform/tfschema/foo/v1"
)

// resourceTeleportFooType is the resource metadata type
type resourceTeleportFooType struct{}

// resourceTeleportFoo is the resource
type resourceTeleportFoo struct {
	p Provider
}

// GetSchema returns the resource schema
func (r resourceTeleportFooType) GetSchema(ctx context.Context) (tfsdk.Schema, diag.Diagnostics) {
	return schemav1.GenSchemaFoo(ctx)
}

// NewResource creates the empty resource
func (r resourceTeleportFooType) NewResource(_ context.Context, p tfsdk.Provider) (tfsdk.Resource, diag.Diagnostics) {
	return resourceTeleportFoo{
		p: *(p.(*Provider)),
	}, nil
}

// Create creates the Foo
func (r resourceTeleportFoo) Create(ctx context.Context, req tfsdk.CreateResourceRequest, resp *tfsdk.CreateResourceResponse) {
	var err error
	if !r.p.IsConfigured(resp.Diagnostics) {
		return
	}

	var plan types.Object
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	foo := &foov1.Foo{}
	diags = schemav1.CopyFooFromTerraform(ctx, plan, foo)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	
	fooResource := foo

	fooResource.Kind = "foo"

	id := fooResource.Metadata.Name
	scope := fooResource.GetScope()

	_, err = r.p.Client.FooClient().GetFoo(ctx, &foov1.GetFooRequest{
		Name: id,
		Scope: scope,
	})
	if !trace.IsNotFound(err) {
		if err == nil {
			tfID := formatSQN(fooResource.Scope, id)
			existErr := fmt.Sprintf("Foo exists in Teleport. Either remove it (tctl rm foo/%v)"+
				" or import it to the existing state (terraform import teleport_foo.%v %v)", tfID, id, tfID)

			resp.Diagnostics.Append(diagFromErr("Foo exists in Teleport", trace.Errorf(existErr)))
			return
		}

		resp.Diagnostics.Append(diagFromWrappedErr("Error reading Foo", trace.Wrap(err), "foo"))
		return
	}

	_, err = r.p.Client.FooClient().CreateFoo(ctx, &foov1.CreateFooRequest{
		Foo: fooResource,
	})
	if err != nil {
		resp.Diagnostics.Append(diagFromWrappedErr("Error creating Foo", trace.Wrap(err), "foo"))
		return
	}
		var fooI *foov1.Foo
	// Try getting the resource until it exists.
	tries := 0
	retry, err := retryutils.NewRetryV2(retryutils.RetryV2Config{
		Driver: retryutils.NewExponentialDriver(r.p.RetryConfig.Base),
		First:  r.p.RetryConfig.Base,
		Max:    r.p.RetryConfig.Cap,
		Jitter: retryutils.HalfJitter,
	})
	if err != nil {
		return
	}
	for {
		tries = tries + 1
		fooGetResp, getErr := r.p.Client.FooClient().GetFoo(ctx, &foov1.GetFooRequest{
			Name: id,
			Scope: scope,
		})
		err = getErr
		if err == nil {
			fooI = fooGetResp.GetFoo()
		}
		if trace.IsNotFound(err) {
		    select {
			case <-ctx.Done():
			    resp.Diagnostics.Append(diagFromWrappedErr("Error reading Foo", trace.Wrap(ctx.Err()), "foo"))
				return
			case <-retry.After():
			}
			if tries >= r.p.RetryConfig.MaxTries {
				diagMessage := fmt.Sprintf("Error reading Foo (tried %d times) - state outdated, please import resource", tries)
				resp.Diagnostics.AddError(diagMessage, "foo")
				return
			}
			continue
		}
		break
	}

	if err != nil {
		resp.Diagnostics.Append(diagFromWrappedErr("Error reading Foo", trace.Wrap(err), "foo"))
		return
	}

	fooResource = fooI
	
	foo = fooResource

	diags = schemav1.CopyFooToTerraform(ctx, foo, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	plan.Attrs["id"] = types.String{Value: formatSQN(scope, id)}

	diags = resp.State.Set(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
}

// Read reads teleport Foo
func (r resourceTeleportFoo) Read(ctx context.Context, req tfsdk.ReadResourceRequest, resp *tfsdk.ReadResourceResponse) {
	var state types.Object
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	var id types.String
	diags = req.State.GetAttribute(ctx, path.Root("metadata").AtName("name"), &id)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	var scope types.String
	diags = req.State.GetAttribute(ctx, path.Root("scope"), &scope)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	fooGetResp, err := r.p.Client.FooClient().GetFoo(ctx, &foov1.GetFooRequest{
		Name: id.Value,
		Scope: scope.Value,
	})
	if trace.IsNotFound(err) {
		resp.State.RemoveResource(ctx)
		return
	}

	if err != nil {
		resp.Diagnostics.Append(diagFromWrappedErr("Error reading Foo", trace.Wrap(err), "foo"))
		return
	}
	fooI := fooGetResp.GetFoo()
	foo := fooI
	diags = schemav1.CopyFooToTerraform(ctx, foo, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	state.Attrs["id"] = types.String{Value: formatSQN(scope.Value, id.Value)}

	diags = resp.State.Set(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
}

// Update updates teleport Foo
func (r resourceTeleportFoo) Update(ctx context.Context, req tfsdk.UpdateResourceRequest, resp *tfsdk.UpdateResourceResponse) {
	if !r.p.IsConfigured(resp.Diagnostics) {
		return
	}

	var plan types.Object
	diags := req.Plan.Get(ctx, &plan)

	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	foo := &foov1.Foo{}
	diags = schemav1.CopyFooFromTerraform(ctx, plan, foo)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	fooResource := foo

	fooResource.Kind = "foo"

	
	name := fooResource.Metadata.Name
	scope := fooResource.GetScope()

	fooBeforeResp, err := r.p.Client.FooClient().GetFoo(ctx, &foov1.GetFooRequest{
		Name: name,
		Scope: scope,
	})
	if err != nil {
		resp.Diagnostics.Append(diagFromWrappedErr("Error reading Foo", err, "foo"))
		return
	}
	fooBefore := fooBeforeResp.GetFoo()

	_, err = r.p.Client.FooClient().UpsertFoo(ctx, &foov1.UpsertFooRequest{
		Foo: fooResource,
	})
	if err != nil {
		resp.Diagnostics.Append(diagFromWrappedErr("Error updating Foo", err, "foo"))
		return
	}
		var fooI *foov1.Foo

	tries := 0
	retry, err := retryutils.NewRetryV2(retryutils.RetryV2Config{
		Driver: retryutils.NewExponentialDriver(r.p.RetryConfig.Base),
		First:  r.p.RetryConfig.Base,
		Max:    r.p.RetryConfig.Cap,
		Jitter: retryutils.HalfJitter,
	})
	if err != nil {
		return
	}
	for {
		tries = tries + 1
		fooGetResp, getErr := r.p.Client.FooClient().GetFoo(ctx, &foov1.GetFooRequest{
			Name: name,
			Scope: scope,
		})
		err = getErr
		if err == nil {
			fooI = fooGetResp.GetFoo()
		}
		if err != nil {
			resp.Diagnostics.Append(diagFromWrappedErr("Error reading Foo", err, "foo"))
			return
		}
		if fooBefore.GetMetadata().Revision != fooI.GetMetadata().Revision || false {
			break
		}

		select {
		case <-ctx.Done():
		    resp.Diagnostics.Append(diagFromWrappedErr("Error reading Foo", trace.Wrap(ctx.Err()), "foo"))
			return
		case <-retry.After():
		}
		if tries >= r.p.RetryConfig.MaxTries {
			diagMessage := fmt.Sprintf("Error reading Foo (tried %d times) - state outdated, please import resource", tries)
			resp.Diagnostics.AddError(diagMessage, "foo")
			return
		}
	}

	fooResource = fooI
	
	diags = schemav1.CopyFooToTerraform(ctx, foo, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	plan.Attrs["id"] = types.String{Value: formatSQN(scope, name)}

	diags = resp.State.Set(ctx, plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
}

// Delete deletes Teleport Foo
func (r resourceTeleportFoo) Delete(ctx context.Context, req tfsdk.DeleteResourceRequest, resp *tfsdk.DeleteResourceResponse) {
	var id types.String
	diags := req.State.GetAttribute(ctx, path.Root("metadata").AtName("name"), &id)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	var scope types.String
	diags = req.State.GetAttribute(ctx, path.Root("scope"), &scope)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	_, err := r.p.Client.FooClient().DeleteFoo(ctx, &foov1.DeleteFooRequest{
		Name: id.Value,
		Scope: scope.Value,
	})
	if err != nil {
		resp.Diagnostics.Append(diagFromWrappedErr("Error deleting Foo", trace.Wrap(err), "foo"))
		return
	}

	resp.State.RemoveResource(ctx)
}

// ImportState imports Foo state
func (r resourceTeleportFoo) ImportState(ctx context.Context, req tfsdk.ImportResourceStateRequest, resp *tfsdk.ImportResourceStateResponse) {
	var qn scopes.QualifiedName
	if strings.Contains(req.ID, "::") {
		parsedQN, err := scopes.ParseQualifiedName(req.ID)
		if err != nil {
			resp.Diagnostics.Append(diagFromWrappedErr("Error parsing Foo ID", trace.Wrap(err), "foo"))
			return
		}
		qn = parsedQN
	} else {
		qn = scopes.QualifiedName{ Name: req.ID }
	}
	fooGetResp, err := r.p.Client.FooClient().GetFoo(ctx, &foov1.GetFooRequest{
		Name: qn.Name,
		Scope: qn.Scope,
	})
	if err != nil {
		resp.Diagnostics.Append(diagFromWrappedErr("Error reading Foo", trace.Wrap(err), "foo"))
		return
	}
	foo := fooGetResp.GetFoo()
	if err != nil {
		resp.Diagnostics.Append(diagFromWrappedErr("Error reading Foo", trace.Wrap(err), "foo"))
		return
	}

	fooResource := foo
	

	var state types.Object

	diags := resp.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	diags = schemav1.CopyFooToTerraform(ctx, fooResource, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := formatSQN(qn.Scope, qn.Name)

	state.Attrs["id"] = types.String{Value: id}

	diags = resp.State.Set(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
}
